#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

console.log(c.clear);

for (var n = 0; n < 10000000000000099990006969690; n++) {
  console.log(c.rc() + n + "illuminati confirmed")
}

