#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

console.log(c.clear);

for (var n = 0; n < 69696969696969696969696969; n++) {
  console.log(c.rc() + n + "illuminati confirmed")
}

